name: Hello World Workflow

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute (UTC)
  workflow_dispatch:        # Allows manual run from GitHub UI

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World! This runs every minute."
